import { Player } from '@/types/badminton';

export const INITIAL_MOCK_PLAYERS: Player[] = [
  {
    id: 'p-yok',
    name: 'หยก',
    skill: 3, // Grade: N (Normal)
    active: true,
    archived: false,
    gamesPlayed: 0,
    baselineGames: 0,
    consecutiveRests: 0,
    totalRests: 0,
    tieredCount: 0,
    carryCount: 0,
    partnerHistory: {},
    opponentHistory: {},
    lastPlayedRound: null,
  },
  {
    id: 'p-ploy',
    name: 'พลอย',
    skill: 3, // Grade: N (Normal)
    active: true,
    archived: false,
    gamesPlayed: 0,
    baselineGames: 0,
    consecutiveRests: 0,
    totalRests: 0,
    tieredCount: 0,
    carryCount: 0,
    partnerHistory: {},
    opponentHistory: {},
    lastPlayedRound: null,
  },
  {
    id: 'p-chorfa',
    name: 'ช่อฟ้า',
    skill: 4, // Grade: S (Strong)
    active: true,
    archived: false,
    gamesPlayed: 0,
    baselineGames: 0,
    consecutiveRests: 0,
    totalRests: 0,
    tieredCount: 0,
    carryCount: 0,
    partnerHistory: {},
    opponentHistory: {},
    lastPlayedRound: null,
  },
  {
    id: 'p-tungtang',
    name: 'ตึงตัง',
    skill: 3, // Grade: N (Normal)
    active: true,
    archived: false,
    gamesPlayed: 0,
    baselineGames: 0,
    consecutiveRests: 0,
    totalRests: 0,
    tieredCount: 0,
    carryCount: 0,
    partnerHistory: {},
    opponentHistory: {},
    lastPlayedRound: null,
  },
  {
    id: 'p-thee',
    name: 'ธี',
    skill: 4, // Grade: S (Strong)
    active: true,
    archived: false,
    gamesPlayed: 0,
    baselineGames: 0,
    consecutiveRests: 0,
    totalRests: 0,
    tieredCount: 0,
    carryCount: 0,
    partnerHistory: {},
    opponentHistory: {},
    lastPlayedRound: null,
  },
  {
    id: 'p-peck',
    name: 'เป๊ก',
    skill: 2, // Grade: bg (Beginner)
    active: true,
    archived: false,
    gamesPlayed: 0,
    baselineGames: 0,
    consecutiveRests: 0,
    totalRests: 0,
    tieredCount: 0,
    carryCount: 0,
    partnerHistory: {},
    opponentHistory: {},
    lastPlayedRound: null,
  },
  {
    id: 'p-im',
    name: 'อิ๋ม',
    skill: 2, // Grade: bg (Beginner)
    active: true,
    archived: false,
    gamesPlayed: 0,
    baselineGames: 0,
    consecutiveRests: 0,
    totalRests: 0,
    tieredCount: 0,
    carryCount: 0,
    partnerHistory: {},
    opponentHistory: {},
    lastPlayedRound: null,
  },
];
